import { type NextPage } from "next";
import Head from "next/head";
import { TrendingList } from "~/components/TrendingList";
import { MoviesList } from "~/components/MoviesList";
import { useGetPopularMovies, useGetPopularSeries } from "~/utils/use-queries";
import Link from "next/link";

const Home: NextPage = () => {
  const [popularMovies] = useGetPopularMovies();
  const [popularSeries] = useGetPopularSeries();

  return (
    <>
      <Head>
        <title>Movies Entertainment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TrendingList />

      <MoviesList 
        movies={popularMovies.slice(0, 12)} 
        title = 'Popular movies'
        category = 'Movie'
        apiPath = 'movie'
      />

      <MoviesList 
        movies={popularSeries.slice(0, 12)} 
        title = 'Popular series'
        category = 'TV Serie'
        apiPath = 'tv'
      />
    </>
  );
};

export default Home;
