import { type NextPage } from "next";
import Head from "next/head";
import { MovieCard } from "~/components/MovieCard";

import { Navbar } from "~/components/Navbar";
import { Searchbar } from "~/components/Searchbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movies Entertainment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-dark font-body text-light lg:pl-40">
        {/* <Navbar />
        <Searchbar /> */}
        <MovieCard />
      </main>
    </>
  );
};

export default Home;
